#!/usr/bin/env python3
"""把 Cursor 私有扩展相关翻译挂到已安装的 zh-hans 语言包 translations 通道。"""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime
from pathlib import Path

from paths import cursor_extensions_dir

ROOT = Path(__file__).resolve().parent.parent
OVERLAY_PATH = ROOT / "data/cursor-overlay.zh-cn.json"
BACKUP_DIR = ROOT / "backups"

# 将 overlay 中常见 Cursor 私有模块映射为语言包扩展翻译文件
# key: 写入语言包 translations/ 下的扩展 id；value: overlay contents 中匹配的模块前缀
PRIVATE_EXTENSION_MAP = {
    "anysphere.cursor-always-local": [
        "vs/workbench/contrib/composer",
        "vs/workbench/contrib/ai",
        "vs/workbench/services/ai",
    ],
    "anysphere.cursor-retrieval": [
        "vs/workbench/contrib/cursorRetrieval",
        "vs/workbench/contrib/cursorIndexing",
    ],
}


def log(msg: str = "") -> None:
    print(msg, flush=True)


def find_language_pack(extensions_dir: Path) -> Path:
    candidates = sorted(
        extensions_dir.glob("ms-ceintl.vscode-language-pack-zh-hans-*"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError("未找到中文语言包，请先运行 ensure-language-pack.py")
    return candidates[0]


def load_package_nls_config(pack_dir: Path) -> tuple[dict, Path]:
    """读取语言包 package.nls 配置：优先 package.json contributes.localizations。"""
    pkg_path = pack_dir / "package.json"
    pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    return pkg, pkg_path


def ensure_translation_files(pack_dir: Path, overlay: dict) -> int:
    """根据 overlay 生成/更新私有扩展 i18n 文件，并注册到 package.json。"""
    pkg, pkg_path = load_package_nls_config(pack_dir)
    localizations = pkg.setdefault("contributes", {}).setdefault("localizations", [])
    zh = None
    for loc in localizations:
        if loc.get("languageId") in ("zh-cn", "zh-hans"):
            zh = loc
            break
    if zh is None:
        zh = {
            "languageId": "zh-cn",
            "languageName": "Chinese Simplified",
            "localizedLanguageName": "中文(简体)",
            "translations": [],
        }
        localizations.append(zh)

    translations = zh.setdefault("translations", [])
    # translations 可能是 list[{id,path}] 或旧格式 dict
    if isinstance(translations, dict):
        # 转为 list 形式便于追加
        translations_list = [{"id": k, "path": v} for k, v in translations.items()]
        zh["translations"] = translations_list
        translations = translations_list

    existing_ids = {t.get("id") for t in translations if isinstance(t, dict)}
    contents = overlay.get("contents", {})
    written = 0
    translations_dir = pack_dir / "translations"
    translations_dir.mkdir(parents=True, exist_ok=True)

    for ext_id, prefixes in PRIVATE_EXTENSION_MAP.items():
        merged: dict[str, dict[str, str]] = {}
        for module, keys in contents.items():
            if any(module.startswith(prefix) for prefix in prefixes):
                merged[module] = keys
        if not merged:
            # 即使 overlay 暂无匹配模块，也写入空壳，便于后续扩展
            continue

        file_name = ext_id.replace("/", ".") + ".i18n.json"
        rel_path = f"./translations/{file_name}"
        abs_path = translations_dir / file_name
        payload = {
            "": ["Generated by bridge-private-extensions.py for Cursor private extensions."],
            "version": "1.0.0",
            "contents": merged,
        }
        old = None
        if abs_path.exists():
            try:
                old = json.loads(abs_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                old = None
        if old != payload:
            BACKUP_DIR.mkdir(parents=True, exist_ok=True)
            if abs_path.exists():
                stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
                shutil.copy2(abs_path, BACKUP_DIR / f"{file_name}.{stamp}.bak")
            abs_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            written += 1
            log(f"  写入桥接翻译: {rel_path} ({sum(len(v) for v in merged.values())} keys)")

        if ext_id not in existing_ids:
            translations.append({"id": ext_id, "path": rel_path})
            existing_ids.add(ext_id)
            written += 1
            log(f"  注册到语言包: {ext_id}")

    # 回写 package.json
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(pkg_path, BACKUP_DIR / f"language-pack-package.json.{stamp}.bak")
    pkg_path.write_text(json.dumps(pkg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description="Bridge Cursor private extension i18n into language pack")
    parser.add_argument("--extensions-dir", default=None)
    args = parser.parse_args()

    if not OVERLAY_PATH.exists():
        log(f"错误: 未找到 {OVERLAY_PATH}")
        return 1

    overlay = json.loads(OVERLAY_PATH.read_text(encoding="utf-8"))
    extensions_dir = Path(args.extensions_dir) if args.extensions_dir else cursor_extensions_dir()

    try:
        pack_dir = find_language_pack(extensions_dir)
    except FileNotFoundError as exc:
        log(f"错误: {exc}")
        return 1

    log(f"语言包: {pack_dir}")
    count = ensure_translation_files(pack_dir, overlay)
    if count == 0:
        log("桥接无变更（可能 overlay 中暂无私有模块匹配，或已是最新）")
    else:
        log(f"桥接完成，变更 {count} 项")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
