#!/usr/bin/env python3
"""向 Cursor workbench.html 注入轻量运行时翻译脚本。

会修改安装目录中的 workbench.html，并写入 cursor-zh-runtime.js，
同时更新 product.json 校验和。支持 Windows / macOS / Linux。
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

from paths import (
    find_cursor_app_root,
    is_windows,
    platform_display_name,
    quit_hint,
    workbench_dir,
    workbench_html_path,
)

ROOT = Path(__file__).resolve().parent.parent
DICT_DIR = ROOT / "data" / "runtime-dicts"
ENGINE_SRC = ROOT / "runtime" / "engine.js"
BACKUP_DIR = ROOT / "backups"

INJECTION_MARKER = "<!-- CURSOR_ZH_HANS_INJECTION -->"
RUNTIME_JS_NAME = "cursor-zh-runtime.js"

WORKBENCH_CHECKSUM_KEYS = (
    "vs/code/electron-sandbox/workbench/workbench.html",
    "vs/code/electron-browser/workbench/workbench.html",
    "out/vs/code/electron-sandbox/workbench/workbench.html",
    "out/vs/code/electron-browser/workbench/workbench.html",
)


def log(msg: str = "") -> None:
    print(msg, flush=True)


def sha256_checksum(data: bytes) -> str:
    return base64.b64encode(hashlib.sha256(data).digest()).decode("ascii").rstrip("=")


def backup_file(source: Path) -> Path:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = BACKUP_DIR / f"{source.name}.{stamp}.bak"
    shutil.copy2(source, backup_path)
    return backup_path


def ensure_writable(app_root: Path) -> None:
    probe = app_root / f".cursor-i18n-write-test-{os.getpid()}"
    try:
        probe.write_text("ok", encoding="utf-8")
        probe.unlink(missing_ok=True)
    except OSError as exc:
        hint = ""
        if is_windows() and "Program Files" in str(app_root):
            hint = "\n提示: 请以管理员身份运行安装脚本。"
        raise PermissionError(f"无法写入 Cursor 安装目录: {app_root}\n原因: {exc}{hint}") from exc


def load_entries(filename: str) -> list:
    path = DICT_DIR / filename
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("entries", [])


def load_patterns() -> list:
    path = DICT_DIR / "patterns.json"
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("patterns", [])


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_runtime_js() -> str:
    if not ENGINE_SRC.exists():
        raise FileNotFoundError(f"未找到运行时引擎: {ENGINE_SRC}")

    exact: dict[str, str] = {}
    for name in ("core.json", "marketplace.json", "notifications.json"):
        for en, zh in load_entries(name):
            exact[en] = zh
    exact_list = [[k, exact[k]] for k in sorted(exact, key=lambda x: (-len(x), x))]
    fragments = load_entries("fragments.json")
    patterns = load_patterns()

    exact_js = ",\n    ".join(f"[{js_string(a)}, {js_string(b)}]" for a, b in exact_list)
    frag_js = ",\n    ".join(f"[{js_string(a)}, {js_string(b)}]" for a, b in fragments)
    pat_js = ",\n    ".join(
        "{"
        + f"regex: {js_string(p['regex'])}, flags: {js_string(p.get('flags', ''))}, "
        + f"replacement: {js_string(p['replacement'])}"
        + "}"
        for p in patterns
    )

    src = ENGINE_SRC.read_text(encoding="utf-8")
    src = src.replace(
        "  // __EXACT_ENTRIES__\n  var EXACT_ENTRIES = [];",
        f"  // __EXACT_ENTRIES__\n  var EXACT_ENTRIES = [\n    {exact_js}\n  ];",
    )
    src = src.replace(
        "  // __PATTERN_ENTRIES__\n  var PATTERN_ENTRIES = [];",
        f"  // __PATTERN_ENTRIES__\n  var PATTERN_ENTRIES = [\n    {pat_js}\n  ];",
    )
    src = src.replace(
        "  // __FRAGMENT_ENTRIES__\n  var FRAGMENT_ENTRIES = [];",
        f"  // __FRAGMENT_ENTRIES__\n  var FRAGMENT_ENTRIES = [\n    {frag_js}\n  ];",
    )
    header = (
        f"/* Generated by inject-runtime.py at {datetime.now().isoformat(timespec='seconds')} */\n"
    )
    return header + src


def strip_injection(html: str) -> str:
    # 去掉标记行与紧随其后的 script 标签
    pattern = re.compile(
        r"\n?\s*" + re.escape(INJECTION_MARKER) + r"\s*\n?\s*"
        r'<script\s+src="\./cursor-zh-runtime\.js"\s*>\s*</script>\s*',
        re.IGNORECASE,
    )
    html = pattern.sub("", html)
    # 兼容仅残留 script 的情况
    html = re.sub(
        r'\n?\s*<script\s+src="\./cursor-zh-runtime\.js"\s*>\s*</script>\s*',
        "",
        html,
        flags=re.IGNORECASE,
    )
    return html


def inject_html(html: str) -> str:
    html = strip_injection(html)
    snippet = f'\n\t{INJECTION_MARKER}\n\t<script src="./{RUNTIME_JS_NAME}"></script>\n'
    if "</body>" in html:
        return html.replace("</body>", f"</body>{snippet}")
    if "</html>" in html:
        return html.replace("</html>", f"{snippet}</html>")
    return html + snippet


def update_workbench_checksum(app_root: Path, html_path: Path) -> bool:
    product_path = app_root / "product.json"
    if not product_path.exists():
        log(f"警告: 未找到 product.json: {product_path}")
        return False

    product = json.loads(product_path.read_text(encoding="utf-8"))
    checksums = product.get("checksums")
    if not isinstance(checksums, dict):
        log("警告: product.json 无 checksums 字段")
        return False

    new_sum = sha256_checksum(html_path.read_bytes())
    updated = False
    for key in list(checksums.keys()):
        norm = key.replace("\\", "/").lower()
        if "workbench.html" in norm:
            if checksums[key] != new_sum:
                log(f"  更新校验和: {key}")
                checksums[key] = new_sum
                updated = True
            else:
                log(f"  校验和已是最新: {key}")
                updated = True  # 视为已处理

    # 若完全没有 workbench.html 键，尝试写入常见键
    if not any("workbench.html" in k.replace("\\", "/").lower() for k in checksums):
        for key in WORKBENCH_CHECKSUM_KEYS:
            if key in checksums or key.startswith("vs/"):
                checksums[key] = new_sum
                log(f"  写入校验和键: {key}")
                updated = True
                break

    if updated:
        backup_file(product_path)
        product["checksums"] = checksums
        product_path.write_text(
            json.dumps(product, ensure_ascii=False, indent="\t") + "\n", encoding="utf-8"
        )
    return updated


def apply_injection(app_root: Path, dry_run: bool = False) -> int:
    html_path = workbench_html_path(app_root)
    js_path = workbench_dir(app_root) / RUNTIME_JS_NAME
    if not html_path.exists():
        log(f"错误: 未找到 workbench.html: {html_path}")
        return 1

    runtime_js = build_runtime_js()
    original_html = html_path.read_text(encoding="utf-8")
    new_html = inject_html(original_html)

    log(f"  workbench.html: {html_path}")
    log(f"  runtime js: {js_path}")
    log(f"  词典精确条目: {runtime_js.count('[')}")  # rough

    if dry_run:
        log("预览模式，未写入")
        return 0

    ensure_writable(app_root)
    if INJECTION_MARKER not in original_html:
        backup_file(html_path)
    html_path.write_text(new_html, encoding="utf-8")
    js_path.write_text(runtime_js, encoding="utf-8")
    update_workbench_checksum(app_root, html_path)
    log("运行时注入完成")
    return 0


def restore_injection(app_root: Path) -> int:
    html_path = workbench_html_path(app_root)
    js_path = workbench_dir(app_root) / RUNTIME_JS_NAME
    if not html_path.exists():
        log(f"错误: 未找到 workbench.html: {html_path}")
        return 1

    ensure_writable(app_root)
    html = html_path.read_text(encoding="utf-8")
    cleaned = strip_injection(html)
    if cleaned != html:
        backup_file(html_path)
        html_path.write_text(cleaned, encoding="utf-8")
        log("已移除 workbench.html 注入标记")
    else:
        log("workbench.html 中未发现注入标记")

    if js_path.exists():
        js_path.unlink()
        log(f"已删除 {RUNTIME_JS_NAME}")

    update_workbench_checksum(app_root, html_path)
    return 0


def fix_checksum_only(app_root: Path) -> int:
    html_path = workbench_html_path(app_root)
    if not html_path.exists():
        log(f"错误: 未找到 workbench.html: {html_path}")
        return 1
    ensure_writable(app_root)
    ok = update_workbench_checksum(app_root, html_path)
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Inject Cursor zh-hans runtime into workbench.html")
    parser.add_argument("--app-root", default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--restore", action="store_true")
    parser.add_argument("--fix-checksum", action="store_true")
    args = parser.parse_args()

    try:
        app_root = find_cursor_app_root(args.app_root)
    except FileNotFoundError as exc:
        log(f"错误: {exc}")
        return 1

    log(f"平台: {platform_display_name()}")
    log(f"Cursor app root: {app_root}")

    try:
        if args.fix_checksum:
            code = fix_checksum_only(app_root)
        elif args.restore:
            code = restore_injection(app_root)
        else:
            code = apply_injection(app_root, dry_run=args.dry_run)
    except PermissionError as exc:
        log(f"错误: {exc}")
        return 1

    if code == 0 and not args.dry_run:
        log(quit_hint())
    return code


if __name__ == "__main__":
    raise SystemExit(main())
